providers = ["nodejs"]

[variables]
  PORT = 3000

[phases.setup]
  nixPkgs = ["nodejs", "npm"]

[phases.install]
  cmds = [
    "npm ci"
  ]

[phases.build]
  cmds = [
    "npm run build"
  ]

[phases.start]
  cmd = "npm run preview -- --host 0.0.0.0 --port $PORT"